# Generated by Django 6.0.1 on 2026-02-01 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_add_payment_schedule_hourly_rate_time_entry'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='timeentry',
            new_name='contracts_t_contrac_4340d1_idx',
            old_name='contracts_t_contrac_te_idx',
        ),
        migrations.RenameIndex(
            model_name='timeentry',
            new_name='contracts_t_contrac_722a27_idx',
            old_name='contracts_t_contrac_date_idx',
        ),
        migrations.RenameIndex(
            model_name='timeentry',
            new_name='contracts_t_provide_0d4676_idx',
            old_name='contracts_t_provide_date_idx',
        ),
        migrations.AlterField(
            model_name='contract',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='Total contract amount (fixed price) or cap (hourly)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
