# Generated by Django 6.0.1 on 2026-01-27 06:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating_type', models.CharField(choices=[('CLIENT_TO_PROVIDER', 'Client to Provider'), ('PROVIDER_TO_CLIENT', 'Provider to Client')], help_text='Type of rating (client to provider or vice versa)', max_length=20)),
                ('score', models.PositiveIntegerField(help_text='Rating score from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Optional comment/review')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(blank=True, help_text='The contract this rating is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='contracts.contract')),
                ('job', models.ForeignKey(blank=True, help_text='The job this rating is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='jobs.job')),
                ('rated_user', models.ForeignKey(help_text='User being rated', on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL)),
                ('rater', models.ForeignKey(help_text='User giving the rating', on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rated_user', '-created_at'], name='ratings_rat_rated_u_28dbf5_idx'), models.Index(fields=['rater', '-created_at'], name='ratings_rat_rater_i_59a8e1_idx'), models.Index(fields=['job', 'rating_type'], name='ratings_rat_job_id_9522dc_idx'), models.Index(fields=['contract', 'rating_type'], name='ratings_rat_contrac_9dbc9f_idx')],
                'unique_together': {('contract', 'rater', 'rating_type'), ('job', 'rater', 'rating_type')},
            },
        ),
    ]
