# Generated by Django 6.0.1 on 2026-02-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='payment_schedule',
            field=models.CharField(choices=[('FIXED', 'Fixed Price'), ('HOURLY', 'Hourly')], default='FIXED', help_text='FIXED = one total price; HOURLY = rate per hour, provider logs hours', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20),
        ),
    ]
