# Generated by Django 6.0.1 on 2026-01-27 06:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('SKILL', 'Skill/Service Type'), ('CERTIFICATION', 'Certification/License'), ('LANGUAGE', 'Language'), ('OTHER', 'Other')], default='SKILL', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='profiles_ta_name_4685b0_idx'), models.Index(fields=['category'], name='profiles_ta_categor_a9c5ab_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceProviderProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('availability_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=20)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('service_radius', models.PositiveIntegerField(blank=True, null=True)),
                ('portfolio_visibility', models.BooleanField(default=True)),
                ('total_jobs_completed', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('stripe_account_id', models.CharField(blank=True, help_text='Stripe Connect account ID (acct_xxx)', max_length=255)),
                ('stripe_account_enabled', models.BooleanField(default=False, help_text='Whether the Stripe account is enabled to receive payments')),
                ('stripe_onboarding_completed', models.BooleanField(default=False, help_text='Whether Stripe onboarding is completed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to='profiles.profile')),
                ('certifications', models.ManyToManyField(blank=True, limit_choices_to={'category': 'CERTIFICATION'}, related_name='certified_providers', to='profiles.tag')),
                ('languages', models.ManyToManyField(blank=True, limit_choices_to={'category': 'LANGUAGE'}, related_name='speakers', to='profiles.tag')),
                ('skills', models.ManyToManyField(blank=True, limit_choices_to={'category': 'SKILL'}, related_name='providers', to='profiles.tag')),
            ],
            options={
                'ordering': ['-average_rating', '-total_jobs_completed'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='profiles.serviceproviderprofile')),
            ],
            options={
                'ordering': ['-start_date', '-is_current'],
                'indexes': [models.Index(fields=['provider', '-start_date'], name='profiles_ex_provide_e8b0b5_idx')],
            },
        ),
    ]
