# Generated by Django 6.0.1 on 2026-01-27 06:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='ETB', help_text='Currency code', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current payment status', max_length=20)),
                ('payment_method', models.CharField(choices=[('STRIPE', 'Stripe'), ('BANK_TRANSFER', 'Bank Transfer'), ('OTHER', 'Other')], default='STRIPE', help_text='Payment method used', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='Stripe PaymentIntent ID', max_length=255)),
                ('stripe_charge_id', models.CharField(blank=True, help_text='Stripe Charge ID', max_length=255)),
                ('stripe_refund_id', models.CharField(blank=True, help_text='Stripe Refund ID if refunded', max_length=255)),
                ('stripe_transfer_id', models.CharField(blank=True, help_text='Stripe Transfer ID to provider account', max_length=255)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, help_text='Platform fee amount (if applicable)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('provider_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount transferred to provider (after platform fee)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True, help_text='Payment description')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata stored as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when payment was completed', null=True)),
                ('failed_at', models.DateTimeField(blank=True, help_text='Timestamp when payment failed', null=True)),
                ('contract', models.ForeignKey(help_text='The contract this payment is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contracts.contract')),
                ('milestone', models.ForeignKey(blank=True, help_text='Optional: Link to a specific milestone', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='contracts.contractmilestone')),
                ('payer', models.ForeignKey(help_text='User making the payment (typically the client)', on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(help_text='User receiving the payment (typically the provider)', on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('CREATED', 'Created'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], help_text='Type of transaction event', max_length=20)),
                ('stripe_event_id', models.CharField(blank=True, help_text='Stripe webhook event ID if applicable', max_length=255)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Transaction details stored as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(help_text='The payment this transaction belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['contract', 'status'], name='payments_pa_contrac_11e5dc_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payer', '-created_at'], name='payments_pa_payer_i_5351f5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['recipient', '-created_at'], name='payments_pa_recipie_719e1e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', '-created_at'], name='payments_pa_status_21ed42_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['stripe_payment_intent_id'], name='payments_pa_stripe__6fe52c_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payment', '-created_at'], name='payments_pa_payment_086bf8_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['stripe_event_id'], name='payments_pa_stripe__36e74d_idx'),
        ),
    ]
