# Generated by Django 6.0.1 on 2026-02-01 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_rename_contracts_t_contrac_te_idx_contracts_t_contrac_4340d1_idx_and_more'),
        ('payments', '0002_add_time_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='milestone',
            field=models.ForeignKey(blank=True, help_text='Optional: Link to a specific milestone (legacy)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='contracts.contractmilestone'),
        ),
    ]
