# Generated by Django 6.0.1 on 2026-01-27 06:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Contract title', max_length=200)),
                ('description', models.TextField(help_text='Detailed contract description and terms')),
                ('terms', models.TextField(help_text='Contract terms and conditions')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total contract amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='ETB', help_text='Currency code', max_length=3)),
                ('start_date', models.DateField(help_text='Contract start date')),
                ('end_date', models.DateField(blank=True, help_text='Contract end date (optional for open-ended contracts)', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_SIGNATURES', 'Pending Signatures'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('TERMINATED', 'Terminated'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='Current contract status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signed_at', models.DateTimeField(blank=True, help_text='Timestamp when both parties signed', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when contract was completed', null=True)),
                ('client', models.ForeignKey(help_text='The client who is hiring', on_delete=django.db.models.deletion.CASCADE, related_name='client_contracts', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, help_text='Optional: Link to a job if contract is created from a job', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='jobs.job')),
                ('job_application', models.ForeignKey(blank=True, help_text='Optional: Link to a job application if contract is created from an application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='jobs.jobapplication')),
                ('provider', models.ForeignKey(help_text='The service provider', on_delete=django.db.models.deletion.CASCADE, related_name='provider_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Milestone title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Milestone description')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount for this milestone', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('due_date', models.DateField(blank=True, help_text='Expected completion date', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current milestone status', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of milestone in the contract')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when milestone was completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(help_text='The contract this milestone belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='contracts.contract')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_signed', models.BooleanField(default=False, help_text='Whether the contract has been signed')),
                ('signature_data', models.TextField(blank=True, help_text='Signature data (can be image data, hash, or text signature)')),
                ('signature_type', models.CharField(choices=[('DIGITAL', 'Digital Signature'), ('IMAGE', 'Image Signature'), ('TEXT', 'Text Signature')], default='DIGITAL', help_text='Type of signature', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which signature was made', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent from which signature was made')),
                ('signed_at', models.DateTimeField(blank=True, help_text='Timestamp when signature was made', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(help_text='The contract being signed', on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='contracts.contract')),
                ('signer', models.ForeignKey(help_text='The user signing the contract', on_delete=django.db.models.deletion.CASCADE, related_name='contract_signatures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['client', 'status', '-created_at'], name='contracts_c_client__f22872_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['provider', 'status', '-created_at'], name='contracts_c_provide_88d48d_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status', '-created_at'], name='contracts_c_status_e5aa9f_idx'),
        ),
        migrations.AddIndex(
            model_name='contractmilestone',
            index=models.Index(fields=['contract', 'status'], name='contracts_c_contrac_f4dd37_idx'),
        ),
        migrations.AddIndex(
            model_name='contractmilestone',
            index=models.Index(fields=['contract', 'order'], name='contracts_c_contrac_aa12c9_idx'),
        ),
        migrations.AddIndex(
            model_name='contractsignature',
            index=models.Index(fields=['contract', 'is_signed'], name='contracts_c_contrac_f96d83_idx'),
        ),
        migrations.AddIndex(
            model_name='contractsignature',
            index=models.Index(fields=['signer', '-signed_at'], name='contracts_c_signer__9f2696_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contractsignature',
            unique_together={('contract', 'signer')},
        ),
    ]
